# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_similarity_matrix_sp <- function(n_items, groups, items) {
    .Call(`_SAR_make_similarity_matrix_sp`, n_items, groups, items)
}

rescale_to_jaccard <- function(mat) {
    .Call(`_SAR_rescale_to_jaccard`, mat)
}

rescale_to_lift <- function(mat) {
    .Call(`_SAR_rescale_to_lift`, mat)
}

user_predict_ranking <- function(aff, sim, n_recs, include_seed_items, backfill, pop_items) {
    .Call(`_SAR_user_predict_ranking`, aff, sim, n_recs, include_seed_items, backfill, pop_items)
}

